CREATE TABLE `input-log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `createTime` DATETIME NOT NULL DEFAULT now(),
  `content` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
